import argparse

args = argparse.ArgumentParser(description='manual to this script')
args.add_argument('--contigs', type=str, default='test_contigs.fa', help=' the file name of the input file')
args.add_argument('--len', type=int, default=8000, help='the minimum input length limit, that is, predict only for sequence >= len bp (default 0)')
args.add_argument('--gpus', type=int, default=0, help='GPU device ID (only used if --use-cpu is not set)')
args.add_argument('--model', type=str, default='pretrain', choices=['pretrain', 'retrain'], help='predicting host with pretrained parameters or retrained paramters (default pretrain)')
args.add_argument('--lr', default=0.001, type=float, help='Learning rate of training')
args.add_argument('--weight-decay', default=0, type=float, help='Weight Decay of optimizer')
args.add_argument('--topk',  type=int, default=1, help='topK')
args.add_argument('--t',  type=float, default=0.98, help='The confident threshold for predicting phages, the higier the threshold the higher the precision. (default 0.98)')
args.add_argument('--epochs', type=int, default=4000, help='Epochs to train')
args.add_argument('--batch-size', type=int, default=512, help='Batch size of Training')
args.add_argument('--GATf', type=int, default=512)
args.add_argument('--GATh', type=int, default=4)
args.add_argument('--head', type=int, default=4)
args.add_argument('--use-cpu', action='store_true', help='Force the use of CPU (default: False)')

inputs = args.parse_args()
print(inputs)
